[project]
name = "medminer"
description = "Project to use LLM agents for text analysis in the medical field"
version = "1.0.0"
license = "MIT"
authors = [
    { name = "Paul-B98", email = "115164840+Paul-B98@users.noreply.github.com" }
]
maintainers = [
    { name = "Paul-B98", email = "115164840+Paul-B98@users.noreply.github.com" }
]
readme = "README.md"
keywords = ["Python Lib", "Doctors letters", "LLM", "AI", "Medical"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.14.0",
    "httpx>=0.28.1",
    "httpx-auth>=0.23.1",
    "langchain>=1.2.17",
    "langchain-openai>=1.2.1",
    "langgraph>=1.1.10",
    "pandas>=3.0.2",
    "pandas-stubs>=3.0.0.260204",
    "pydantic-settings>=2.14.0",
    "rich>=15.0.0",
    "typer>=0.25.1",
]

[project.urls]
homepage = "https://github.com/aidh-ms/MedMiner"
repository = "https://github.com/aidh-ms/MedMiner"
changelog = "https://github.com/aidh-ms/MedMiner/releases"
issues = "https://github.com/aidh-ms/MedMiner/issues"
documentation = "https://github.com/aidh-ms/MedMiner/wiki"

[project.scripts]
medminer = "medminer.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab>=4.5.7",
    "openpyxl>=3.1.5",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.15.13",
    "ty>=0.0.34",
]
docs = [
    "mkdocs>=1.6.1",
]

[tool.uv]
exclude-newer = "P7D"

[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py"]
filterwarnings = ["ignore::DeprecationWarning"]
pythonpath = ["src"]
cache_dir = "/workspaces/.cache/pytest"
addopts = [
    "--cov",
    "--cov-branch",
    "--cov=src",
    "--cov-report=xml",
    "--import-mode=importlib",
]
